### ISSUE TITLE
Reduce the amount of Javascript files loaded

### ISSUE THREAD

**Issue by lucsoft** [i-voted-for-biden2/howoldisjava8.today#19]
Why does this simple website need 10 Javascript files?

It looks like you are using webpack then bind it into one chunk

**Comment by DRSchlaubi** [comment]
> Why does this simple website need 10 Javascript files?
Because it's nuxt and javascript, a language where a lib advertises it's new version by WE NOW HAVE 60% LESS DEPENDENCIES

**Comment by lucsoft** [comment]
why can nuxt not just give me the pre fetch language thing?

**Comment by DRSchlaubi** [comment]
How do I know that. I am not a webdev

**Comment by DRSchlaubi** [comment]
Let's just close this with the obligatory JS SUCKS notice

**Comment by NyCodeGHG** [comment]
I think that's a question everyone has to answer for themselves. I also think that @DRSchlaubi and I are of a different opinion :)

**Comment by DRSchlaubi** [comment]
> Javascript > Kotlin

I don't exactly understand how the language which has a commonly useed tool called webpack which produces 10 js files for a simple website like this is better than Kotlin could you elaborate that?

**Comment by lucsoft** [comment]
no its not webpack
its nuxt.js and all of this layers
