### ISSUE TITLE
Switch from 3rd party time hoster to new Date()

### ISSUE THREAD

**Issue by lucsoft** [i-voted-for-biden2/howoldisjava8.today#20]
![image](https://user-images.githubusercontent.com/11093382/110371659-94125a80-804d-11eb-8c9d-d74f9bc185f8.png)

https://howoldisjava8.today/de/ sometimes dosn't load the time and it throws an cors error

**Comment by DRSchlaubi** [comment]
the API was added for a reason, so the site is not affected in case the system time is off, although I have noticed as well that worldtimeapi.org is kinda trash

**Comment by lucsoft** [comment]
yeah but you can never trust time and for this simple website its easy to get the time by the server or just use javascript

**Comment by DRSchlaubi** [comment]
Yes it's easier but the whole point of this site is, to make fun of a) how old Java 8 is and b) How easy it is to make a site that only shows one line of thex consit of 25k lines of code

**Comment by lucsoft** [comment]
a) jup and i love the 1.8.8 thing

b) oh this is a joke? i really thought this was real, i just made does tickets because why the hell you need kotlin and next.js for this simple this (like next.js is a bit overrated)

**Comment by DRSchlaubi** [comment]
>  oh this is a joke?
Ofc You thought I would make serious js stuff?
> why the hell you need kotlin 
Kotlin is only used for the Android App and the Discord bot, the website is vue and ts
> and next.js for this simple this (like next.js is a bit overrated)
1) Nuxt.js*
2) I couldn't get plain vue to do what I want it to do. And I wanted to use vue because this also is a vue learning project

**Comment by DRSchlaubi** [comment]
That got fixed somewhere I guess
